/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1/samples
 */

plugins {
    java
    `maven-publish`
}

group = "me.sniper10754.nitroxide"
version = "0.1"

repositories {
    mavenLocal()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    compileOnly("com.github.Sniper10754:SimpleLogger4j:master-SNAPSHOT")
}